// Autogenerated by cmake
// DO NOT EDIT

#pragma once
#define CRY_Enabled 0
#define TENSORFLOW_Enabled 1

#include <string>

namespace RAT {

static const std::string RATVERSION = "9d6bb77";

}  // namespace RAT
